
# base for the image
FROM debian:buster 

# running commands to install needed programs
RUN 

# output from the DF 
WORKDIR [path]

# copy files/dir to container
COPY [source] [destination]

# define ports that the container will listen to
EXPOSE [portnb]

#start the container
CMD ["name", etc]
